version: '3.9'

services:
  postgres:
    container_name: 'java-postgres'
    image: 'postgres:15'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: child
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 5050:5050
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/child
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  pgdata:
